git:
  log:
    showWholeGraph: true
  pagers:
    - pager: 'delta --paging=never --features "catppuccin-mocha" --line-numbers --navigate --true-color=always'
gui:
  filterMode: fuzzy
  nerdFontsVersion: "3"
  shortTimeFormat: 03:04
  timeFormat: 02 Jan 2006
update:
  method: never
